<?php
/**
 *
 * This file is part of the American English Language Pack
 * for the phpBB Forum Software.
 *
 * @copyright (c) phpBB Limited <https://www.phpbb.com>
 * @license GNU General Public License, version 2 (GPL-2.0)
 *
 * For full copyright and license information, please see
 * the docs/CREDITS.txt file.
 *
 */

/**
 * DO NOT CHANGE
 */
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

$lang = array_merge($lang, array(
	'HELP_BBCODE_BLOCK_IMAGES'	=> 'Показване на изображения в мнения',
	'HELP_BBCODE_BLOCK_INTRO'	=> 'Въведение',
	'HELP_BBCODE_BLOCK_LINKS'	=> 'Създаване на връзки',
	'HELP_BBCODE_BLOCK_LISTS'	=> 'Генериране на списъци',
	'HELP_BBCODE_BLOCK_OTHERS'	=> 'Дуриг',
	'HELP_BBCODE_BLOCK_QUOTES'	=> 'Цитиране',
	'HELP_BBCODE_BLOCK_TEXT'	=> 'Текстово форматиране',

	'HELP_BBCODE_IMAGES_ATTACHMENT_ANSWER'	=> 'Прикачените файлове могат да бъдат поставяни навсякъде в мнението с <strong>[attachment=][/attachment]</strong> кода, в случай че функцията за прикачени файлове е пусната и вие имате нужните права. Може да поставяте прикачените файлове на същият ред, като изберете това от падащото меню.',
	'HELP_BBCODE_IMAGES_ATTACHMENT_QUESTION'	=> 'Добавяне на приначени файлове към мнение',
	'HELP_BBCODE_IMAGES_BASIC_ANSWER'	=> 'BB кодовете включват тагове за добавяне на изображения към мнения. Two very important things to remember when using this tag are: many users do not appreciate lots of images being shown in posts and secondly the image you display must already be available on the internet (it cannot exist only on your computer for example, unless you run a webserver!). To display an image you must surround the URL pointing to the image with <strong>[img][/img]</strong> tags. For example:<br /><br /><strong>[img]</strong>https://www.phpbb.com/theme/images/logos/blue/160x52.png<strong>[/img]</strong><br /><br />As noted in the URL section above you can wrap an image in a <strong>[url][/url]</strong> tag if you wish, e.g.<br /><br /><strong>[url=https://www.phpbb.com/][img]</strong>https://www.phpbb.com/theme/images/logos/blue/160x52.png<strong>[/img][/url]</strong><br /><br />would generate:<br /><br /><a href="https://www.phpbb.com/"><img src="https://www.phpbb.com/theme/images/logos/blue/160x52.png" alt="" /></a>',
	'HELP_BBCODE_IMAGES_BASIC_QUESTION'	=> 'Добавяне на изображение в мнение',

	'HELP_BBCODE_INTRO_BBCODE_ANSWER'	=> 'BB кодовете са специална имплементация на HTML. Форумният администратор преценява дали BB кодовете може да се използват. В допълнение можете да деактивирате BBCode на база публикуване чрез формата за публикуване. Самият BBCode е подобен на стил като HTML, таговете са затворени в квадратни скоби [ и ], а не %lt; и &gt; и предлага по-голям контрол върху това какво и как се показва нещо. В зависимост от шаблона, който използвате, може да откриете, че добавянето на BBCode към вашите публикации е много по-лесно чрез интерфейс, който може да се кликва, над областта за съобщения във формата за публикуване. Дори и с това може да намерите следното ръководство за полезно.',
	'HELP_BBCODE_INTRO_BBCODE_QUESTION'	=> 'Какво е BB код?',

	'HELP_BBCODE_LINKS_BASIC_ANSWER'	=> 'BBCode в phpBB поддържа няколко начина за създаване на URI адреси (Uniform Resource Indicators), по-известни като URL адреси.<ul><li>Първият използва тага <strong>[url=][/url]</strong>; всичко, което въведете след знака =, ще направи съдържанието на този таг връзка към URL адрес. Например за връзка към phpBB.com можете да използвате:<br /><br /><strong>[url=https://www.phpbb.com/]</strong>Посетете phpBB!<strong>[/url]</strong><br /><br />Това ще създаде следната връзка: <a href="https://www.phpbb.com/">Посетете phpBB!</a>. Имайте предвид, че връзката ще се отвори в същия или в нов прозорец според настройките на браузъра на потребителя.</li><li>Ако искате самият URL адрес да се показва като връзка, можете просто да използвате:<br /><br /><strong>[url]</strong>https://www.phpbb.com/<strong>[/url]</strong><br /><br />Това ще създаде следната връзка: <a href="https://www.phpbb.com/">https://www.phpbb.com/</a></li><li>Освен това phpBB предлага т.нар. <i>магически връзки</i>, които превръщат всеки синтактично правилен URL адрес във връзка, без да е необходимо да посочвате тагове или дори началното http://. Например, ако въведете www.phpbb.com в съобщението си, при преглед то автоматично ще се покаже като <a href="http://www.phpbb.com/">www.phpbb.com</a>.</li><li>Същото важи и за имейл адресите: можете изрично да посочите адрес, например:<br /><br /><strong>[email]</strong>no.one@domain.adr<strong>[/email]</strong><br /><br />което ще изведе <a href="mailto:no.one@domain.adr">no.one@domain.adr</a>, или просто да въведете no.one@domain.adr в съобщението си и той ще бъде автоматично преобразуван при преглед.</li></ul>Както при всички BBCode тагове, можете да поставяте URL адреси около други тагове, например <strong>[img][/img]</strong> (вижте следващия запис), <strong>[b][/b]</strong> и др. Както при форматиращите тагове, Ваша отговорност е да спазите правилния ред на отваряне и затваряне. Например:<br /><br /><strong>[url=https://www.phpbb.com/][img]</strong>https://www.phpbb.com/theme/images/logos/blue/160x52.png<strong>[/url][/img]</strong><br /><br />е <span style="text-decoration: underline">неправилно</span>, защото първият таг трябва да бъде затворен след тага за изображение.',
	'HELP_BBCODE_LINKS_BASIC_QUESTION'	=> 'Връзки към други сайтове',

	'HELP_BBCODE_LISTS_ORDERER_ANSWER'	=> 'Вторият тип списък, подреденият списък, Ви позволява да контролирате какво се показва преди всеки елемент. За да създадете подреден списък, използвайте <strong>[list=1][/list]</strong> за номериран списък или <strong>[list=a][/list]</strong> за азбучен списък. Както при неподредения списък, елементите се задават чрез <strong>[*]</strong>. Например:<br /><br /><strong>[list=1]</strong><br /><strong>[*]</strong>Отидете до магазина<br /><strong>[*]</strong>Купете нов компютър<br /><strong>[*]</strong>Ядосайте се на компютъра, когато забие<br /><strong>[/list]</strong><br /><br />ще създаде следното:<ol style="list-style-type: decimal;"><li>Отидете до магазина</li><li>Купете нов компютър</li><li>Ядосайте се на компютъра, когато забие</li></ol>За азбучен списък използвайте:<br /><br /><strong>[list=a]</strong><br /><strong>[*]</strong>Първият възможен отговор<br /><strong>[*]</strong>Вторият възможен отговор<br /><strong>[*]</strong>Третият възможен отговор<br /><strong>[/list]</strong><br /><br />което дава<ol style="list-style-type: lower-alpha"><li>Първият възможен отговор</li><li>Вторият възможен отговор</li><li>Третият възможен отговор</li></ol><br /><strong>[list=A]</strong><br /><strong>[*]</strong>Първият възможен отговор<br /><strong>[*]</strong>Вторият възможен отговор<br /><strong>[*]</strong>Третият възможен отговор<br /><strong>[/list]</strong><br /><br />което дава<ol style="list-style-type: upper-alpha"><li>Първият възможен отговор</li><li>Вторият възможен отговор</li><li>Третият възможен отговор</li></ol><br /><strong>[list=i]</strong><br /><strong>[*]</strong>Първият възможен отговор<br /><strong>[*]</strong>Вторият възможен отговор<br /><strong>[*]</strong>Третият възможен отговор<br /><strong>[/list]</strong><br /><br />което дава<ol style="list-style-type: lower-roman"><li>Първият възможен отговор</li><li>Вторият възможен отговор</li><li>Третият възможен отговор</li></ol><br /><strong>[list=I]</strong><br /><strong>[*]</strong>Първият възможен отговор<br /><strong>[*]</strong>Вторият възможен отговор<br /><strong>[*]</strong>Третият възможен отговор<br /><strong>[/list]</strong><br /><br />което дава<ol style="list-style-type: upper-roman"><li>Първият възможен отговор</li><li>Вторият възможен отговор</li><li>Третият възможен отговор</li></ol>',
	'HELP_BBCODE_LISTS_ORDERER_QUESTION'	=> 'Създаване на Подреден Списък',
	'HELP_BBCODE_LISTS_UNORDERER_ANSWER'	=> 'BBCode поддържа два вида списъци: неподредени и подредени. Те по същество са същите като HTML еквивалентите си. Неподреденият списък извежда всеки елемент последователно, като го отмества и маркира с водещ знак. За да създадете неподреден списък, използвайте <strong>[list][/list]</strong> и задайте всеки елемент в списъка със <strong>[*]</strong>. Например, за да изброите любимите си цветове, можете да използвате:<br /><br /><strong>[list]</strong><br /><strong>[*]</strong>Червено<br /><strong>[*]</strong>Синьо<br /><strong>[*]</strong>Жълто<br /><strong>[/list]</strong><br /><br />Това ще създаде следния списък:<ul><li>Червено</li><li>Синьо</li><li>Жълто</li></ul><br />Можете също да посочите стила на водещия знак чрез <strong>[list=disc][/list]</strong>, <strong>[list=circle][/list]</strong> или <strong>[list=square][/list]</strong>.',
	'HELP_BBCODE_LISTS_UNORDERER_QUESTION'	=> 'Създаване на Неподреден Списък',

	'HELP_BBCODE_OTHERS_CUSTOM_ANSWER'	=> 'Ако сте администратор на този форум и имате подходящите разрешения, можете да добавите допълнителни BBCodes чрез секцията Персонализирани BBCodes.',
	'HELP_BBCODE_OTHERS_CUSTOM_QUESTION'	=> 'Мога ли да добавям мой тагове?',

	'HELP_BBCODE_QUOTES_CODE_ANSWER'	=> 'Ако искате да изведете парче код или всъщност всичко, което изисква фиксирана ширина, напр. Шрифт на куриерския тип, трябва да затворите текста в <strong> [code] [/code] </strong> тагове, напр. <br /> <br /> <strong> [code] </strong> echo „Това е някакъв код "<strong> [/code] </strong> <br /> <br /> Цялото форматиране, използвано в маркерите <strong> [code] [/code] </strong>, се запазва, когато го прегледате по-късно.',
	'HELP_BBCODE_QUOTES_CODE_QUESTION'	=> 'Изходен код или данни с фиксирана ширина',
	'HELP_BBCODE_QUOTES_TEXT_ANSWER'	=> 'Има два начина да цитирате текст: с препратка или без.<ul><li>Когато използвате функцията за цитиране, за да отговорите на мнение във форума, ще забележите, че текстът на мнението се добавя в полето за съобщение, ограден в блок <strong>[quote=&quot;&quot;][/quote]</strong>. Този метод позволява да цитирате с препратка към човек или към каквото друго изберете. Например, за да цитирате текст, написан от Mr. Blobby, въведете:<br /><br /><strong>[quote=&quot;Mr. Blobby&quot;]</strong>Тук ще бъде текстът, написан от Mr. Blobby<strong>[/quote]</strong><br /><br />Полученият резултат автоматично ще добави &quot;Mr. Blobby wrote:&quot; преди самия текст. Не забравяйте, че <strong>трябва</strong> да включите кавичките &quot;&quot; около името, което цитирате; те не са по избор.</li><li>Вторият метод позволява да цитирате без препратка. За да го използвате, оградете текста с таговете <strong>[quote][/quote]</strong>. При преглед съобщението просто ще покаже текста в цитатен блок.</li></ul>',
	'HELP_BBCODE_QUOTES_TEXT_QUESTION'	=> 'Цитиране на текст в отговор',

	'HELP_BBCODE_TEXT_BASIC_ANSWER'	=> 'BBCode включва тагове, за да ви позволи бързо да промените основния стил на вашия текст. Това се постига по следните начини: <ul> <li> За да направите парче текст удебелен, го затворете в <strong> [b] [/b] </strong>, напр. <br /> <br /> <strong> [b] </strong> Здравей <strong> [/b] </strong> <br /> <br /> ще стане <strong> Здравей </strong> </li> <li> За подчертаване използвайте <strong> [u] [/u] </strong>, например: <br /> <br /> <strong> [u] </strong> Добро утро <strong> [/u] </strong> <br /> <br /> става <span style="text-decoration: underline"> Добро утро </span> </li> <li> За курсив на текст използвайте <strong> [i] [/i] </strong>, напр. <br /> <br /> Това е <strong> [i] </strong> Чудесно! <strong> [/i] </strong> <br /> <br /> би дал Това е <i> Great!</i></li> </ul>',
	'HELP_BBCODE_TEXT_BASIC_QUESTION'	=> 'Създаване на удебелен, наклонен или подчертан текст',
	'HELP_BBCODE_TEXT_COLOR_ANSWER'	=> 'За да промените цвета или размера на текста си, можете да използвате следните тагове. Имайте предвид, че крайният вид зависи от браузъра и системата на читателя: <ul><li>Цветът на текста се променя, като го оградите с <strong>[color=][/color]</strong>. Можете да посочите разпознато име на цвят (напр. red, blue, yellow и др.) или шестнадесетична стойност, напр. #FFFFFF, #000000. Например, за да създадете червен текст, можете да използвате:<br /><br /><strong>[color=red]</strong>Здравейте!<strong>[/color]</strong><br /><br />или<br /><br /><strong>[color=#FF0000]</strong>Здравейте!<strong>[/color]</strong><br /><br />И двата варианта ще изведат <span style="color:red">Здравейте!</span></li><li>Размерът на текста се променя по подобен начин чрез <strong>[size=][/size]</strong>. Този таг зависи от избрания от потребителя шаблон, но препоръчителният формат е числова стойност, представяща размера на текста в проценти, по подразбиране от 20 (много малък) до 200 (много голям). Например:<br /><br /><strong>[size=30]</strong>МАЛЪК<strong>[/size]</strong><br /><br />обикновено ще бъде <span style="font-size:30%;">МАЛЪК</span><br /><br />докато:<br /><br /><strong>[size=200]</strong>ОГРОМЕН!<strong>[/size]</strong><br /><br />ще бъде <span style="font-size:200%;">ОГРОМЕН!</span></li></ul>',
	'HELP_BBCODE_TEXT_COLOR_QUESTION'	=> 'Как да променя цвета на текста или размера',
	'HELP_BBCODE_TEXT_COMBINE_ANSWER'	=> 'Да, разбира се. Например, за да привлечете нечие внимание, можете да напишете:<br /><br /><strong>[size=200][color=red][b]</strong>ВИЖТЕ МЕ!<strong>[/b][/color][/size]</strong><br /><br />това ще изведе <span style="color:red;font-size:200%;"><strong>ВИЖТЕ МЕ!</strong></span><br /><br />Не препоръчваме обаче да публикувате много текст, който изглежда така. Не забравяйте, че Ваша отговорност като автор е таговете да бъдат затворени правилно. Например следното е неправилно:<br /><br /><strong>[b][u]</strong>Това е грешно<strong>[/b][/u]</strong>',
	'HELP_BBCODE_TEXT_COMBINE_QUESTION'	=> 'Може ли да се комбинират форматиращи тагове?',
));
